name: Test Kubesec

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Lint code
        uses: kubesec/kubesec@master
        run: kubesec scan .kubsec/kubesec.yml
