name: Test Kubesec

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Kubesec Download
        run: |
          wget https://github.com/kubesec/kubesec/releases/download/v0.17.0/kubesec-linux-amd64
          chmod +x kubesec-linux-amd64
          sudo mv kubesec-linux-amd64 /usr/local/bin/kubesec

      - name: Kubesec scan
        run: |
          kubesec .kubsec/demo.yml
