name: Test Kubesec

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Kubesec Download
        run: |
          wget https://github.com/controlplaneio/kubesec/releases/download/v2.14.0/kubesec_linux_amd64.tar.gz
          tar -xvf kubesec_linux_amd64.tar.gz
          chmod +x kubesec
          sudo mv kubesec /usr/local/bin
          ls

      - name: Kubesec scan
        continue-on-error: true
        run: |
          kubesec scan kubse/demo.yml --format json > report.json
          if [ $? -ne 0 ]; then
            exit 1
          fi

      - name: Read report
        run: |
          python3 kubse/main.py

